bitcoin:
  rpc:
    url: 'http://localhost:18443'
  grpc:
    url: 'localhost:8080'
lightning:
  ping_interval: 0
  dust_limit_satoshis: 546
  max_htlc_value_in_flight_msat: 100_000
  reserve_to_funding_ratio: 0.01
  htlc_minimum_msat: 0
  delay_blocks: 144
  max_accepted_htlcs: 300
  globalfeatures: '00'
  localfeatures: '80'
  feerates_per_kw: 46_080
  chain_hash: '06226e46111a0b59caaf126043eb5bbf28c34f3a5e332a1fc7b2b73cf188910f'
  min_depth_blocks: 1
  fee_base_msat: 1_000
  fee_proportional_millionths: 100
  expiry_delta_blocks: 144
  maximum_feerate_per_kw: 100_000_000
  minimum_feerate_per_kw: 253
